-- Campus Equipment Booking API - data model (SQLite / Cloudflare D1)
-- Safe to run more than once: tables are created only if missing and seed rows are not duplicated.

-- NOT NULL is written on the primary keys on purpose: SQLite allows NULL in a non-integer PRIMARY KEY.
CREATE TABLE IF NOT EXISTS equipment (
  id       TEXT PRIMARY KEY NOT NULL,     -- e.g. 'eq-1'
  name     TEXT NOT NULL,
  location TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id            TEXT PRIMARY KEY NOT NULL, -- UUID generated by the API
  equipment_id  TEXT NOT NULL REFERENCES equipment(id),
  borrower_name TEXT NOT NULL,
  start_at      TEXT NOT NULL,            -- ISO 8601 UTC, e.g. '2026-10-20T09:00:00.000Z'
  end_at        TEXT NOT NULL,            -- ISO 8601 UTC, same fixed format
  purpose       TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  CHECK (start_at < end_at)
);

-- Supports the overlap check: "bookings of this equipment that touch this time range"
CREATE INDEX IF NOT EXISTS idx_bookings_equipment_time
  ON bookings (equipment_id, start_at, end_at);

-- Seed data (the brief asks for at least two equipment records)
INSERT OR IGNORE INTO equipment (id, name, location) VALUES
  ('eq-1', 'Projector A', 'Building 1'),
  ('eq-2', 'Camera B', 'Building 2'),
  ('eq-3', 'Meeting Room C', 'Library, 2nd floor');
